
# this is the directory where input image files are placed and where the output files will be stored


#DATA_PATH: "/Users/Ashwini/Desktop/CMSC-630/Cancerous cell smears 2023/Cancerous cell smears"
#OUTPUT_PATH: "/Users/Ashwini/Desktop/CMSC-630/output/"

DATA_PATH: ".../Cancerous cell smears"
OUTPUT_PATH: ".../CMSC-630/output/"

#WIN_DATA_DIR: "C:/Users/Owner/Desktop/CMSC-630/Cancerous cell smears 2023/Cancerous cell smears"
#WIN_OUTPUT_DIR: "C:/Users/Owner/Desktop/CMSC-630/output/"

WIN_DATA_DIR: ".../Cancerous cell smears"
WIN_OUTPUT_DIR: ".../CMSC-630/output/"

#DATASET_OUTPUT: "/Users/Ashwini/CMSC-630/output/dataset.csv"
DATASET_OUTPUT: ".../output/dataset.csv"

# select color channel to convert to greyscale from with options as red, green, blue
SELECTED_COLOR_CHANNEL: "red"

# salt and pepper noise, gaussian noise value between 0-1
SNP_NOISE: 0.2
G_NOISE: 0.9

# numeric data type as string, ie. double, int 
QUANT_STRENGTH: "int"

# linear filtering : a 2D array of odd size equal to mask, 3x3=9, 5x5=25 ...
LINEAR_MASK: 9
LINEAR_WEIGHT: [[1, 1, 1],
               [1, 1, 1],
               [1, 1 ,1]]

# median 2D array of odd size equal to mask, 3x3=9, 5x5=25 ...
MEDIAN_MASK: 9
MEDIAN_WEIGHT: [[1, 1, 1],
               [1, 1, 1],
               [1, 1 ,1]]

#  k-value for k-means clustering specified by user, the value used here is 2
K_VALUE: 2